### ISSUE TITLE
keybindings.json lint warning

### ISSUE THREAD

**Issue by tberghuis** [ctf0/macros#1]
Plugin works great!
Is it possible to suppress the lint error/warning shown in screenshot.
Thanks
![macros bug](https://user-images.githubusercontent.com/7745506/58774348-55dc4180-8604-11e9-84a1-8bcf1abcea66.png)

**Comment by ctf0** [comment]
this is related to vscode it self not recognizing the command as an internal one or inside any ext as we create them dynamically

**Comment by ctf0** [comment]
**UPDATE**

i dont have this issue anymore with the latest vscode insider
