### ISSUE TITLE
Reference for VScode actions that needs arguments

### ISSUE THREAD

**Issue by hyh19962008** [ctf0/macros#10]
Post it here in case someone needs it. 
[Built-in Commands](https://code.visualstudio.com/api/references/commands)
Note that simple-commands that can be found in the Keyboard Shortcuts list doesn't use argument.
[Built-in Commands#simple-commands](https://code.visualstudio.com/api/references/commands#simple-commands)

**Comment by ctf0** [comment]
can u make a PR to update the rdme with them instead ?

**Comment by hyh19962008** [comment]
will do
