### ISSUE TITLE
Select options in quick picker

### ISSUE THREAD

**Issue by PabloLION** [ctf0/macros#15]
Hi all. I'm new to this extension and I thought VS Code should have a native macro recorder like excel/google spreadsheet but it doesnt. This extension is amazing. But I am having some trouble using it.
# background
I have a bunch of UTF-16 LE encoded files and I am trying to convert them to UTF-8 in VSCode. It's easy to do it with quick picker -"Change File Encoding" - "Save with Encoding" - "UTF-8"
# the question
I'm trying to interact with the qiuck picker. Is it possible? If so, how?
I tried: 
1. write the option directly
2. use `{"command": "type", "args": {"text": ";" }}`
3. i read [extension guides](https://code.visualstudio.com/api/extension-guides/overview) trying to find some commands to interact with quick picker but i have not found anything.

here's the corresponding json 
```JSONC
  "macros.saveAsUTF8": [
    "workbench.action.editor.changeEncoding", //"Change File Encoding",
    /* test1
     * "Save with Encoding",
     * "UTF-8"
     */
    // test 2  {"command": "type", "args": {"text": ";" }},
  ]
```

**Comment by ctf0** [comment]
the command should be under the `macros.list` config ex.
```js
"macros.list": {
  "saveAsUTF8": [
    "workbench.action.editor.changeEncoding",
    // do something else
  ]
```

**Comment by ctf0** [comment]
however flow like this wont work with the ext, sadly u will have to create ur own ext to automate the dropdown selection, maybe this could help https://github.com/ctf0/macros/issues/9

**Comment by PabloLION** [comment]
> the command should be under the `macros.list` config ex.
> 
> ```js
> "macros.list": {
>   "saveAsUTF8": [
>     "workbench.action.editor.changeEncoding",
>     // do something else
>   ]
> ```

with `macros.saveAsUTF8` it also works (with hotkey). You cant try it XD.
I'll close this issue since it is not possible to achieve. Feel free to reopen it if you want to add this feature when VSCode empowers us. 
May the force be with you.
