### ISSUE TITLE
How to trigger an activation event

### ISSUE THREAD

**Issue by ADTC** [ctf0/macros#16]
Is there a way to directly trigger [an activation event](https://code.visualstudio.com/api/references/activation-events)?

```
    "macros.list": {
        "myMacro": [
            {
                "command": "vscode.openWith",
                "args": {
                    "viewId": "myCustomEditor"
                }
            }
        ]
    }
```

To give a bit of context, I'm trying to re-open a file in a custom editor (setting it as default didn't work — caponetto/vscode-diff-viewer#26).

The command `workbench.action.reopenWithEditor` would launch the quick picker, but it seems there's no way to interact with the quick picker in the macro. The execution pauses, and would only resume when the quick picker is dismissed.

**Comment by ctf0** [comment]
sadly its not possible, u will have to create ur own ext for that :(
