### ISSUE TITLE
Pass string concatenation as an argument to some command

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [ctf0/macros#17]
My goal is to create macros to add new Git feature/bugfix branches. For instance, I execute macros named `Git: Create feature branch` and type just branch name, then it should create a branch named like this: `feature/<name>`. AFAIK there is no ability to directly concatenate strings, but maybe there is a command to insert `feature/` prefix in a field where user types branch name?

**Comment by ctf0** [comment]
sadly this is not possible atm, the extension is basically a helper to access other extensions cmnds but i have an rough idea of
- create a service cmnd to show a popup where the user add some text
- add that string to the clipboard
- the user create a snippet with a placeholder for the clipboard data https://code.visualstudio.com/docs/editor/userdefinedsnippets#_snippet-syntax
- use insert snippet like so https://github.com/ctf0/macros#executing-snippets-as-part-of-a-macro
- 🚀

**Comment by ctf0** [comment]
>  but maybe there is a command to insert feature/ prefix in a field where user types branch name?

for this i think u can use https://github.com/ctf0/macros#passing-arguments-to-commands
