### ISSUE TITLE
Sometimes macro doesn't complete

### ISSUE THREAD

**Issue by martinakos** [ctf0/macros#18]
I have this macro:

```
    "macros.list": {
        "evaluate_comment": [            
            "editor.action.commentLine",
            "editor.debug.action.selectionToRepl",
            "undo"
        ]
    },
```

I use it to evaluate sections of commented code in the python debug console while in a breakpoint. 
If I select a block of code that doesn't take long to execute when sent to the debug console the undo step takes place.
However, if the code takes longer to execute, then undo step never takes place. 

Any idea how to work around this so that the undo step always takes place?

**Comment by ctf0** [comment]
u can add a delay https://github.com/ctf0/macros#run-commands-with-a-delay

**Comment by martinakos** [comment]
Thanks for the quick reply. I've tried this:
```
    "macros.list": {
        "evaluate_comment": [            
            "editor.action.commentLine",         
            "editor.debug.action.selectionToRepl",
            {
                "command": "$delay",
                "args": {
                    "delay": 1
                }
            }, 
            "undo"                        
        ]
    },
```
However, the problem is still there. I've tried with delays of up to 10 (I assume these are seconds?). When I select blocks of codes that execute quickly the undo takes place, it doesn't for blocks of code that take longer to execute.

**Comment by ctf0** [comment]
milliseconds, so 1000 = 1 second

**Comment by martinakos** [comment]
Ok. I see. I've set it to 2000 and I see the selection is uncommented, then wait 2s, then sent to the debug console, then undo the uncommenting. The issue is still there, when selecting blocks of code that take longer to execute the undo doesn't happen, just now there is a 2s pause before  sending it to the debug console.

**Comment by martinakos** [comment]
Maybe some issue with thread timeouts?

**Comment by ctf0** [comment]
the thing is we can never know when the cmnd will finish execution.

**Comment by martinakos** [comment]
I found a workaround.

```
    "macros.list": {
        "evaluate_comment": [            
            "editor.action.commentLine",    
            "editor.action.clipboardCopyAction",     
            "undo",
            "workbench.debug.action.focusRepl",
            "debug.replPaste",
            "repl.action.acceptInput"
        ]        
    },
```

Basically, uncomment, copy, undo, and copy in the debug console, press enter. 

Thanks for your help and for this extension.
