### ISSUE TITLE
Autocompletion for macro actions

### ISSUE THREAD

**Issue by jd-solanki** [ctf0/macros#19]
Hi 👋🏻 

Thanks for creating this extension. While writing my custom macro how can I know of available macros? like cursorUp and others?

Adding autocompletion for this actions will be greatly useful.

Thanks.

**Comment by ctf0** [comment]
thats a good idea, will see if i can add it, thanks

**Comment by ctf0** [comment]
sorry for the delay, it should be available now in the next releaste.
