### ISSUE TITLE
keybindings don't work

### ISSUE THREAD

**Issue by maricn** [ctf0/macros#2]
### Problem
How to properly setup keybindings to invoke the macros? I've used the old extension with keybindings without problems but now they stopped working.

### My approach
I've updated my User `settings.json` to append `.list` to `macros` object.
It looks like this now:
```
  "macros.list": {
    "formatAndOrganizeImports": [
      "editor.action.organizeImports",
      { "command": "$delay", "args": { "delay": 200 } },
      "editor.action.formatDocument"
    ]
  },
```
And my `keybindings.json` contains:
```
  {
    "key": "alt+cmd+l",
    "when": "editorTextFocus && !editorReadonly && supportedCodeAction =~ /(\\s|^)source\\.organizeImports\\b/ && editorHasDocumentFormattingProvider",
    "command": "macros.formatAndOrganizeImports"
  },
```

#### Results
The keybinding is detected and passes the `when` condition, and then tries to invoke the command, but it results in error:
```
⚠️ command 'macros.formatAndOrganizeImports' not found
```

The command appears in command palette list on `Macros: Execute` and is executed properly from there.

### Thanks
Thanks for making the extension and sharing it! 🖤

**Comment by ctf0** [comment]
have u restarted the editor ? "its not really needed but vscode stops everything when any extension stops working"

**Comment by maricn** [comment]
@ctf0 Yeah, that seems to solve the issue. 😊 I usually keep it open for weeks, didn't occur to me it would change behavior since it's working from the palette. You learn something new every day.. Thanks!
