### ISSUE TITLE
Recent vscode update broke macros key input sequence

### ISSUE THREAD

**Issue by soimy** [ctf0/macros#20]
I have a macro that add quote pairs with a new line
``` json
"endQuote": [
    "editor.action.insertLineAfter",
    {"command": "type", "args": {"text": "{}"}},
    "cursorLeft",
    {"command": "type", "args": {"text": "\n"}},
]
```
But after resent vscode update, the input is odd, leading wrong input sequence on `cursorLeft`

**Comment by ctf0** [comment]
can u plz check the dev-tools for any errors, also u might need to add some delay in between the cmnds because sometimes vscode cant run cmnds too quick.

**Comment by ctf0** [comment]
u probably need to add delay, check https://github.com/ctf0/macros#new
