### ISSUE TITLE
Macros:Execute doesn't show all macros

### ISSUE THREAD

**Issue by marcelloh** [ctf0/macros#4]
The thing is that in my user settings, the example macro shows up in a different color, even if I shrink the setting to this:
```
{
	"macros": {
		"commentDown": [
			"editor.action.copyLinesDownAction",
			"cursorUp",
			"editor.action.addCommentLine",
			"cursorDown"
		]
	},
}
```
and when I try to do the [control} + [command] + [/] it complains about macros.commentDown not existing.
Am I doing something wrong?

**Comment by ctf0** [comment]
actually it should be `macros.list`

**Comment by marcelloh** [comment]
macros.list is not recognized as valid command :-( "no commands matching"
(it only shows "Macros: Execute") with : inbetween....

**Comment by ctf0** [comment]
i meant the settings https://github.com/ctf0/macros#new

```
{
	"macros.list": {
		"commentDown": [
			"editor.action.copyLinesDownAction",
			"cursorUp",
			"editor.action.addCommentLine",
			"cursorDown"
		]
	},
}
```

**Comment by marcelloh** [comment]
ok, now the color seems ok :-)
and for when I try to do the [control} + [command] + [/] it still complains about macros.commentDown not existing. (should that be: macros.list.commentDown?)

**Comment by marcelloh** [comment]
Macros: Execute then select commentDown doesn't do anything (the first time it even closed all my open editors)

**Comment by ctf0** [comment]
to run the command its `macros.commentDown`, u can test to run the command with a shortcut first to make sure its working.

i found that sometimes running multiple consecutive commands need some delay in between otherwise nothing happens, so try 
```
{
    "macros.list": {
        "commentDown": [
            "editor.action.copyLinesDownAction",
            "macros.delay-10",
            "cursorUp",
            "macros.delay-10",
            "editor.action.addCommentLine",
            "macros.delay-10",
            "cursorDown"
        ],
        "delay-10": [
            {
                "command": "$delay",
                "args": {
                    "delay": 10
                }
            }
        ],
    },
}
```

**Comment by marcelloh** [comment]
Somehow, your code works, while mine didn't. Even after removing the delays, it still works :-)
Thanks for the help!
