### ISSUE TITLE
Command inside configuration doesn't work

### ISSUE THREAD

**Issue by ottopic** [ctf0/macros#5]
Hello,
I'm coming from geddski original extension, but with last VS Code update it doesn't work anymore.
Now I'm trying to reproduce macro with your extension, but it seem that using "command" it doesn't work:

```
"macros.list": {
        "printr": [
            "editor.action.smartSelect.grow",
            "editor.action.clipboardCopyAction",
            "editor.action.insertLineAfter",
            {
             "command": "editor.action.insertSnippet",
                "args": {
                    "name": "customprintr",
                    "langId": "php",
                }
           },
           "editor.action.insertLineAfter",
           "editor.action.clipboardCopyAction",
        ]
    }, 
```

Can you help me?

**Comment by ottopic** [comment]
Ok solved rebooting SO.  🙄

**Comment by ctf0** [comment]
btw most of the extensions doesn't work directly after installation and it still requires the editor to be restarted
