### ISSUE TITLE
Docs for extension still use "macros" instead of "macros.list" 

### ISSUE THREAD

**Issue by murphyke** [ctf0/macros#6]
To be clear, when I added this extension just now, the docs for the extension within VS Code say:

Original
Create Custom Macros
Create your own custom macros ...
For example:
"macros": {
...

Lower down you have examples of "macros.list", but I didn't notice that and had to search the issues in the repo.

BTW, thanks for the improved extension!

**Comment by ctf0** [comment]
yeah, i forgot to create new release for vscode to pickup the rdme changes, will do that shortly
