### ISSUE TITLE
Move cursor to next space

### ISSUE THREAD

**Issue by robertmarkbram** [ctf0/macros#9]
I am trying to write a macro that will move the cursor to the next space (like control left/right but ONLY  move to the next space, ignoring all other special characters). I have tried a couple of times before (https://github.com/geddski/macros/issues/49, https://github.com/egodigital/vscode-powertools/issues/26) but haven't worked it out.

Any hints with this extension would be appreciated.

Rob
:)

**Comment by ctf0** [comment]
sadly for cases like this there is no direct solution other than creating an extension that does what u want & incorporate it into a macro. 😢

**Comment by robertmarkbram** [comment]
Oh. :( Thanks for responding and letting me know.

Macros in UltraEdit is the thing I miss most after moving to VS Code. It was easy to do it there.

**Comment by robertmarkbram** [comment]
Can you give arguments to find?

This works, if the the last thing I searched for was the regex '[^ ] '

```
        "goNextSpace": [
            "actions.find",
            "editor.action.nextMatchFindAction",
            "closeFindWidget",
            "cursorRight"
        ]
```

**Comment by ctf0** [comment]
find cant have args, the only way around is to use copy / paste.

**Comment by ctf0** [comment]
https://stackoverflow.com/questions/59300624/how-to-find-the-parameters-for-a-vscode-command-in-executecommands

**Comment by robertmarkbram** [comment]
Got this to work using [vscode-powertools at last](https://github.com/egodigital/vscode-powertools/issues/26#issuecomment-735230643)
